language: node_js

node_js:
  - "8"

os:
  - windows
  - linux
  - osx

branches:
  only:
    - master

cache: npm

before_install:
  -

install:
  - npm install

before_script:
  -

script:
  - npm test

after_success:
  - npm run cover

after_failure:
  -

after_script:
  -
